# Generated by Django 2.0.4 on 2018-06-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('passw', models.CharField(max_length=200, verbose_name='Password')),
                ('color', models.CharField(max_length=200, verbose_name='Colors')),
                ('date', models.DateTimeField(max_length=200, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Gestion Elève',
                'verbose_name_plural': 'Gestion Elèves',
            },
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Choix de question', 'verbose_name_plural': 'Choix de Questions'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question a poser', 'verbose_name_plural': 'Questions a poser'},
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=200, verbose_name='Choix'),
        ),
    ]
