# Generated by Django 2.0.4 on 2018-06-15 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_student_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': (('can_update', 'can update'), ('can_delete', 'can delete user')), 'verbose_name': 'Gestion Elève', 'verbose_name_plural': 'Gestion Elèves'},
        ),
    ]
